[workspace]
members = [
    "native",
    "host",
]
resolver = "2"

[workspace.dependencies]
embedded-hal = "1.0.0"
# PR with embedded-hal v1 support
hd44780-driver = { git = "https://github.com/ichdenkenicht/hd44780-driver.git" }
rppal = { version = "0.17.0", features = ["hal"] }
