[workspace]
members = [
    "native",
    "host",
    "guest"
]
resolver = "2"

[workspace.dependencies]
embedded-hal = "0.2.7"
hd44780-driver = "0.4.0"
rppal = { version = "0.16.0", features = ["hal"] }
