[package]
name = "screen_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = { workspace = true }
hd44780-driver = { workspace = true }
rppal = { workspace = true }
